apiVersion: v1
kind: Service
metadata:
  name: my-app-service          # The name of your app's service
  labels:
    app: my-app
spec:
  selector:
    app: my-app                 # Must match the label in the Deployment
  ports:
    - protocol: TCP
      port: 8000                # Port for internal communication
      targetPort: 8000          # Port on which your app container exposes metrics
  type: ClusterIP               # Internal access; use LoadBalancer for external access
